### ISSUE TITLE
Bildirimler açılmıyor

### ISSUE THREAD

**Issue by INorthDev** [metwcc/www.metw.cc#20]
Bildirimler sayfasına gitmeye çalışınca beklenmedik bir hata oluştu diyor
![Screenshot_20220925-144947_Brave.jpg](https://user-images.githubusercontent.com/80062997/192141962-eb6134b9-0bc2-4013-abe8-666a54ef7059.jpg)

**Comment by metwse** [comment]
@everyone'de de çökmüş

**Comment by metwse** [comment]
Düzelmiş olmalı (database ile alakalı)
