### ISSUE TITLE
Kendi mesajım bana bildirim olarak geliyor

### ISSUE THREAD

**Issue by INorthDev** [metwcc/www.metw.cc#8]
![Screenshot_20220910-212004_Brave.jpg](https://user-images.githubusercontent.com/80062997/189496664-9265cd1c-a8b7-467d-8b49-83014170dd16.jpg)

**Comment by metwse** [comment]
Ah evet, benim de başıma pek sık geliyor... Düzeltmek içim yapmam gereken:
![SmartSelect_20220911-151433_GitHub.jpg](https://user-images.githubusercontent.com/108795071/189526963-0af10ed9-9890-4e3d-a24e-fd185ef1634e.jpg)
kodunun önüne if (userId != req.user.id) koymak, ama hep unutuyorum be...

**Comment by metwse** [comment]
Düzeltildi
![Screenshot 2022-10-08 113852](https://user-images.githubusercontent.com/108795071/194716480-5cd58347-5fe1-4e8a-9498-1c2ec2959f11.png)
